### ISSUE TITLE
Error when place ChunkMiner!

### ISSUE THREAD

**Issue by Marcobagastruz** [SaberLLC/SaberCoreX#1]
ERROR]: Could not pass event BlockPlaceEvent to SaberCoreX v1.1-RC
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-TacoSpigot-04511af6]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [spigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [spigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:131) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:161) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:524) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:750) [?:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-TacoSpigot-04511af6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:809) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:821) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:748) [spigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:649) [spigot.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.listeners.FactionsBlockListener.playerCanBuildDestroyBlock(Lorg/bukkit/entity/Player;Lorg/bukkit/Location;Ljava/lang/String;Z)Z
        at me.driftay.core.hooks.impl.factions.FactionUUIDHook.canBuild(FactionUUIDHook.java:12) ~[?:?]
        at me.driftay.core.modules.chunkbuster.Chunkbusters$ChunkbustersListener.onBusterPlace(Chunkbusters.java:108) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[spigot.jar:git-TacoSpigot-04511af6]
        ... 19 more

**Comment by Driftay** [comment]
You don't have factions in
