### ISSUE TITLE
Error with break spawner!

### ISSUE THREAD

**Issue by Marcobagastruz** [SaberLLC/SaberCoreX#2]
Could not pass event BlockBreakEvent to SaberCoreX v1.1-RC
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-TacoSpigot-04511af6]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-TacoSpigot-04511af6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-TacoSpigot-04511af6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [spigot.jar:git-TacoSpigot-04511af6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:125) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:605) [?:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-TacoSpigot-04511af6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:809) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:821) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:748) [spigot.jar:git-TacoSpigot-04511af6]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:649) [spigot.jar:git-TacoSpigot-04511af6]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.Faction.getRelationTo(Lcom/massivecraft/factions/iface/RelationParticipator;)Lcom/massivecraft/factions/struct/Relation;
	at me.driftay.core.modules.AntiSpawnerMine$AntiSpawnerMineListener.nearbyEnemies(AntiSpawnerMine.java:64) ~[?:?]
	at me.driftay.core.modules.AntiSpawnerMine$AntiSpawnerMineListener.onSpawnerMine(AntiSpawnerMine.java:50) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[spigot.jar:git-TacoSpigot-04511af6]
	... 18 more

**Comment by Driftay** [comment]
You don't have SaberFactions in
